### ISSUE TITLE
Add yeelight to requirements.txt

### ISSUE THREAD

**Issue by jerome3o** [Samueljbk/yeelight_server#10]
After installing reqs with `pip install -r requirements.txt` and running the server with `uvicorn src.be.app:app --reload --port 8000` I get this error:

```
(venv) ✔ ~/source/yeelight_server [learning-continued|✔] 
08:59 $ uvicorn src.be.app:app --reload --port 8000
INFO:     Will watch for changes in these directories: ['/home/jerome/source/yeelight_server']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [1449471] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jerome/source/yeelight_server/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/jerome/source/yeelight_server/venv/lib/python3.10/site-packages/uvicorn/server.py", line 59, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/jerome/source/yeelight_server/venv/lib/python3.10/site-packages/uvicorn/server.py", line 66, in serve
    config.load()
  File "/home/jerome/source/yeelight_server/venv/lib/python3.10/site-packages/uvicorn/config.py", line 471, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/jerome/source/yeelight_server/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/jerome/source/yeelight_server/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jerome/source/yeelight_server/src/be/app.py", line 4, in <module>
    from yeelight import Bulb, discover_bulbs
ModuleNotFoundError: No module named 'yeelight'
```

I think it's because yeelight isn't in the requirements.txt file

**Comment by Samueljbk** [comment]
Fixed, accidently added 0.8.0 instead of 0.7.10
